relaton/support#7 move to external workflow
relaton/relaton-data-rfcsubseries pull request #2
Opened 2023-03-12 21:51 UTC by CAMOBAP

- relaton/support#7

2023-03-13 16:46 UTC, andrew2net commented
@CAMOBAP we are going generate `index.yaml` files for all the `relaton-data-*` repositories. So we need the GHA to zip `index.yaml` into `index.zip` and add the files to commit.
Some repositories already have `index.yaml`, but their format will be changed. For back compatablity I'm going to keep old indexes alogside with new. For example the `relaton-data-bipm` has an old `index.*` and a new `index-bipm.*` So we need to commit these new indexes too.

2023-03-13 16:52 UTC, CAMOBAP commented
@andrew2net I see several options here we can run `git add index.yaml` in https://github.com/relaton/support/blob/master/.github/workflows/crawler.yml#L29 or in `crawler.rb` individually for each repo

I think generic crawler.yml looks better for this, I will prepare PR

2023-03-13 17:27 UTC, andrew2net commented
> I think generic crawler.yml looks better for this, I will prepare PR

Let's make the `crawler.yml` to check if `index.yaml` anf `index-new.yaml` exists. If one or both files exist, zip them into `index.zip` and `index-new.zip` and commit.

2023-03-13 17:29 UTC, andrew2net commented
And we need to remove `index.*` and `index-new.*` before run document fetching.

2023-03-13 18:02 UTC, CAMOBAP commented
> And we need to remove `index.*` and `index-new.*` files before run document fetching.

https://github.com/relaton/support/pull/8 - ready for review

2023-03-13 18:14 UTC, andrew2net commented
> > And we need to remove `index.*` and `index-new.*` files before run document fetching.
> 
> [relaton/support#8](https://github.com/relaton/support/pull/8) - ready for review

I changed my mind. Lets

2023-03-13 19:00 UTC, CAMOBAP commented
@andrew2net if there is no objections on this PR please approve

2023-03-14 00:54 UTC, andrew2net requested changes

2023-03-14 00:54 UTC, andrew2net commented on crawler.rb
> +puts "Done in: #{(t2 - t1).round} sec."
We don't need these messages here. The `relaton-ietf` does it aready.

2023-03-14 00:54 UTC, andrew2net commented on crawler.rb
> +system("relaton fetch-data ietf-rfcsubseries")
Use `RelatonIetf::DataFetcher.fetch("ietf-rfcsubseries")` istead `system`. It works much faster.

2023-03-14 00:54 UTC, andrew2net commented on Gemfile
> +gem 'relaton-iana'
I think we don't need the `relaton-iana` here.

2023-03-14 00:54 UTC, andrew2net commented on crawler.rb
> +require 'fileutils'
To call the data fetcher directly (without calling `system`) we need to add `require "relaton_ietf"` line.

2023-03-14 00:54 UTC, andrew2net commented on .github/workflows/crawler.yml
> +        description: Extra args to pass to crawler.rb script
Can you describe what is this argument used for?

2023-03-14 05:55 UTC, CAMOBAP commented on crawler.rb
> +puts "Done in: #{(t2 - t1).round} sec."
Done

2023-03-14 05:55 UTC, CAMOBAP commented on Gemfile
> +gem 'relaton-iana'
Done

2023-03-14 05:55 UTC, CAMOBAP commented on crawler.rb
> +require 'fileutils'
Done

2023-03-14 06:05 UTC, CAMOBAP commented on .github/workflows/crawler.yml
> +        description: Extra args to pass to crawler.rb script
Generally, the idea of this `args` is to be passed to `crawler.rb` script like this https://github.com/relaton/support/blob/master/.github/workflows/crawler.yml#L24 .

In case we need to do fetch with a specific command like we do in https://github.com/relaton/relaton-data-3gpp/pull/3

In this exact repo, it makes no sense because `crawler.rb` don't handle it. And it is here just because `cimas` tool do mass copy of https://github.com/relaton/support/blob/master/cimas-config/gh-actions/data/crawler.yml workflow

@andrew2net how do you feel about this? Is it ok to keep useless args (let's say for the future) or better remove them?

2023-03-14 06:05 UTC, CAMOBAP commented on crawler.rb
> +system("relaton fetch-data ietf-rfcsubseries")
Done

2023-03-14 16:32 UTC, andrew2net requested changes

2023-03-14 16:32 UTC, andrew2net commented on Gemfile
> +gem 'relaton-cli'
It doesn't need the relaton-cli when we use direct call without `system` CLI call.

2023-03-14 16:32 UTC, andrew2net commented on .github/workflows/crawler.yml
> +        description: Extra args to pass to crawler.rb script
@CAMOBAP I think it's not a big problem to have useless args, but I'd rather remove them if it's possible.

2023-03-14 20:48 UTC, CAMOBAP commented on .github/workflows/crawler.yml
> +        description: Extra args to pass to crawler.rb script
Agree, removed

2023-03-14 20:48 UTC, CAMOBAP commented on Gemfile
> +gem 'relaton-cli'
Done

2023-03-14 20:58 UTC, andrew2net approved these changes

2023-03-14 20:58 UTC, merged